# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jcapy.core.proto import jcapy_pb2 as jcapy_dot_core_dot_proto_dot_jcapy__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in src/jcapy/core/proto/jcapy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JCapyOrchestratorStub(object):
    """JCapyOrchestrator is the primary interface for JCapy 2.0 Brain (jcapyd).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteCommand = channel.unary_unary(
                '/jcapy.JCapyOrchestrator/ExecuteCommand',
                request_serializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.CommandRequest.SerializeToString,
                response_deserializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/jcapy.JCapyOrchestrator/StreamLogs',
                request_serializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.LogRequest.SerializeToString,
                response_deserializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.LogEntry.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/jcapy.JCapyOrchestrator/GetStatus',
                request_serializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.StatusRequest.SerializeToString,
                response_deserializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.RequestApproval = channel.unary_unary(
                '/jcapy.JCapyOrchestrator/RequestApproval',
                request_serializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.ApprovalRequest.SerializeToString,
                response_deserializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.ApprovalResponse.FromString,
                _registered_method=True)


class JCapyOrchestratorServicer(object):
    """JCapyOrchestrator is the primary interface for JCapy 2.0 Brain (jcapyd).
    """

    def ExecuteCommand(self, request, context):
        """Execute a command on the daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Stream real-time logs from the daemon.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get current daemon status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestApproval(self, request, context):
        """Request approval for a sensitive action (Security Proxy).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JCapyOrchestratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.CommandRequest.FromString,
                    response_serializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.CommandResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.LogRequest.FromString,
                    response_serializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.LogEntry.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.StatusRequest.FromString,
                    response_serializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.StatusResponse.SerializeToString,
            ),
            'RequestApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestApproval,
                    request_deserializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.ApprovalRequest.FromString,
                    response_serializer=jcapy_dot_core_dot_proto_dot_jcapy__pb2.ApprovalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jcapy.JCapyOrchestrator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jcapy.JCapyOrchestrator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JCapyOrchestrator(object):
    """JCapyOrchestrator is the primary interface for JCapy 2.0 Brain (jcapyd).
    """

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jcapy.JCapyOrchestrator/ExecuteCommand',
            jcapy_dot_core_dot_proto_dot_jcapy__pb2.CommandRequest.SerializeToString,
            jcapy_dot_core_dot_proto_dot_jcapy__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jcapy.JCapyOrchestrator/StreamLogs',
            jcapy_dot_core_dot_proto_dot_jcapy__pb2.LogRequest.SerializeToString,
            jcapy_dot_core_dot_proto_dot_jcapy__pb2.LogEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jcapy.JCapyOrchestrator/GetStatus',
            jcapy_dot_core_dot_proto_dot_jcapy__pb2.StatusRequest.SerializeToString,
            jcapy_dot_core_dot_proto_dot_jcapy__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jcapy.JCapyOrchestrator/RequestApproval',
            jcapy_dot_core_dot_proto_dot_jcapy__pb2.ApprovalRequest.SerializeToString,
            jcapy_dot_core_dot_proto_dot_jcapy__pb2.ApprovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
