# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/jcapy/core/proto/jcapy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'src/jcapy/core/proto/jcapy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n src/jcapy/core/proto/jcapy.proto\x12\x05jcapy\"\x8a\x01\n\x0e\x43ommandRequest\x12\x13\n\x0b\x63ommand_str\x18\x01 \x01(\t\x12\x33\n\x07\x63ontext\x18\x02 \x03(\x0b\x32\".jcapy.CommandRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"L\n\x0f\x43ommandResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x18\n\x10result_data_json\x18\x03 \x01(\t\"\x1c\n\nLogRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\"M\n\x08LogEntry\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\r\n\x05level\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"\x0f\n\rStatusRequest\"a\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x02 \x01(\x05\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x16\n\x0e\x61\x63tive_persona\x18\x04 \x01(\t\"S\n\x0f\x41pprovalRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x1a\n\x12\x61\x63tion_description\x18\x02 \x01(\t\x12\x12\n\nrisk_level\x18\x03 \x01(\t\"4\n\x10\x41pprovalResponse\x12\x10\n\x08\x61pproved\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2\x86\x02\n\x11JCapyOrchestrator\x12?\n\x0e\x45xecuteCommand\x12\x15.jcapy.CommandRequest\x1a\x16.jcapy.CommandResponse\x12\x32\n\nStreamLogs\x12\x11.jcapy.LogRequest\x1a\x0f.jcapy.LogEntry0\x01\x12\x38\n\tGetStatus\x12\x14.jcapy.StatusRequest\x1a\x15.jcapy.StatusResponse\x12\x42\n\x0fRequestApproval\x12\x16.jcapy.ApprovalRequest\x1a\x17.jcapy.ApprovalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.jcapy.core.proto.jcapy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_COMMANDREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_COMMANDREQUEST']._serialized_start=44
  _globals['_COMMANDREQUEST']._serialized_end=182
  _globals['_COMMANDREQUEST_CONTEXTENTRY']._serialized_start=136
  _globals['_COMMANDREQUEST_CONTEXTENTRY']._serialized_end=182
  _globals['_COMMANDRESPONSE']._serialized_start=184
  _globals['_COMMANDRESPONSE']._serialized_end=260
  _globals['_LOGREQUEST']._serialized_start=262
  _globals['_LOGREQUEST']._serialized_end=290
  _globals['_LOGENTRY']._serialized_start=292
  _globals['_LOGENTRY']._serialized_end=369
  _globals['_STATUSREQUEST']._serialized_start=371
  _globals['_STATUSREQUEST']._serialized_end=386
  _globals['_STATUSRESPONSE']._serialized_start=388
  _globals['_STATUSRESPONSE']._serialized_end=485
  _globals['_APPROVALREQUEST']._serialized_start=487
  _globals['_APPROVALREQUEST']._serialized_end=570
  _globals['_APPROVALRESPONSE']._serialized_start=572
  _globals['_APPROVALRESPONSE']._serialized_end=624
  _globals['_JCAPYORCHESTRATOR']._serialized_start=627
  _globals['_JCAPYORCHESTRATOR']._serialized_end=889
# @@protoc_insertion_point(module_scope)
